### ISSUE TITLE
Follow typography guidelines

### ISSUE THREAD

**Issue by pablojimpas** [gtk-flutter/adwaita#12]
Typography is really important for the look and feel of UIs.

If we want to build accurate GNOME style apps this Adwaita theme should follow [HIG Guidelines on Typography](https://developer.gnome.org/hig/guidelines/typography.html) closely. Specifically they use the `Cantarell` font, I think it is included in the `google_fonts` package although adding such a big dependency for a small feature seems bloated, it will be better to include it manually, here is [Cantarell's official page](https://cantarell.gnome.org/).

**Comment by MalcolmMielle** [comment]
The guideline says the [Wherever possible, use the default system fonts as provided by the distribution or operating system on which your application is running](https://developer.gnome.org/hig/guidelines/typography.html#general-guidelines). This would mean that in android and ios we don't want to change the font to Cantarell.

I have no idea how fonts are handled in flutter for desktop, on the other hand. Would you have the time to check that out and see if it follows the system's default already? I'm under the impressoin that the Ubuntu people [do not need to handle that in their yaru package](https://github.com/ubuntu/yaru.dart)

**Comment by pablojimpas** [comment]
Flutter apps use the default font provided by the engine, they don't follow system's default font. https://github.com/flutter/flutter/issues/48381

It seems like Ubuntu's Yaru theme provides it's own font family: https://github.com/ubuntu/yaru.dart/tree/main/lib/src/text

I think we could do something similar in this package with Cantarell since it is GNOME default font regardless of the guidelines saying that apps should follow the default system theme since Flutter doesn't support that for now.

**Comment by MalcolmMielle** [comment]
Yep good catch I missed that earlier. Would be ok with sending a PR doing that? It would be awesome!

**Comment by prateekmedia** [comment]
1:1 Typography is coming in v0.5.0
![image](https://user-images.githubusercontent.com/41370460/153474717-59356023-aaac-402f-9a6d-5cf4947f61f0.png)
