### ISSUE TITLE
Adwaita theme on listtiles

### ISSUE THREAD

**Issue by CodeDoctorDE** [gtk-flutter/adwaita#16]
Hello,
I want to give a native look and feel to my app.
![image](https://user-images.githubusercontent.com/20452814/176875801-4d5d3b8f-d0cc-4527-8cdd-05655af9582c.png)
But I found out that the listtiles has a different look than in the screenshot.

**Comment by prateekmedia** [comment]
This ain't a List tile, It's from Sidebar

**Comment by CodeDoctorDE** [comment]
How can I use this styles?
![image](https://user-images.githubusercontent.com/20452814/176876571-3ff5bc83-da40-4516-8715-5137c983b7bf.png)
Currently I'm using listtiles for my sidebar

**Comment by prateekmedia** [comment]
The example is available at https://github.com/gtk-flutter/libadwaita/blob/main/example/lib/home_page.dart at Line 158.

You can see that for best practices.

**Comment by CodeDoctorDE** [comment]
Hmm, I'm currently using the material widgets. I will see how to integrate this...
