### ISSUE TITLE
Wrap themes inside a class

### ISSUE THREAD

**Issue by jesusrp98** [gtk-flutter/adwaita#5]
Wrapping both dark and light themes into a class called `AdwaitaThemeData` or something similar would make its use much easier for the developer.

This
``` dart
import 'package:adwaita/adwaita.dart' as adwaita;

return MaterialApp(
  theme: adwaita.lightTheme,
  darkTheme: adwaita.darkTheme,
);
```

could be this
``` dart
import 'package:adwaita/adwaita.dart';

return MaterialApp(
  theme: AdwaitaThemeData.light(),
  darkTheme: AdwaitaThemeData.dark(),
);
```

You could have to different methods inside that class (light and dark) that would generate the appropriate `ThemeData` instance.

This is how it's done on the material side of things.

Let me know what you think about this change. I could take this issue and create a PR for it if you want it :)

**Comment by MalcolmMielle** [comment]
That sounds good to me :). Feel free to send in a PR !
