### ISSUE TITLE
Missing `analysis_options.yaml` file

### ISSUE THREAD

**Issue by jesusrp98** [gtk-flutter/adwaita#8]
This file is missing from the project, because it's included inside the `.gitignore` file.

Is there a reason this file is not uploaded to remote?

**Comment by prateekmedia** [comment]
No reason, just a mistake.

**Comment by MalcolmMielle** [comment]
It is a file that is in the local project I have, but I didn't want to publish. Should I remove it?

**Comment by prateekmedia** [comment]
@MalcolmMielle You can publish it, If it doesn't contain anything or is too long then you can use the content of this file:
https://github.com/gtk-flutter/libadwaita/blob/main/analysis_options.yaml

Also don't forget to remove this from `.gitignore`.

**Comment by MalcolmMielle** [comment]
Closed with a0c7967
